name: 'EditorConfig-Action'
description: 'A GitHub Action to check, enforce & fix EditorConfig style violations'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'eye'
  color: 'yellow'
