name: ShellCheck Linting

on: [push]

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout VCS
        uses: actions/checkout@v1

      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
